### ISSUE TITLE
[Rosetta] Fix Event hash check

### ISSUE THREAD

**Issue by koko1123** [onflow/rosetta#41]
## Problem

The [event hash check ](https://github.com/onflow/rosetta/blob/f4c85daff526e85f9132d217302692a2a475250c/state/process.go#L317-L324) in rosetta fails due to incomplete and json-formatted transaction results. We have disabled this check but want this to be made possible again for BFT reasons.

## Solution

Rosetta's hash computation should be corrected by: 
- converting the payload format to the correct `CCF` format
- requesting the full event payload, including system events in the given block

**Comment by j1010001** [comment]
post mortem: https://www.notion.so/dapperlabs/Coinbase-Withdrawal-and-Deposits-have-stopped-c22dee31d9c24964a7b7d95c832b4ea3?pvs=4

**Comment by koko1123** [comment]
https://github.com/onflow/rosetta/pull/49/files

**Comment by j1010001** [comment]
Changes to the Access API are live now, this can be completed
