### ISSUE TITLE
Error building Docker image

### ISSUE THREAD

**Issue by Palak3196** [onflow/rosetta#9]
Hi team,

I cloned the Rosetta repo with command: `git clone https://github.com/onflow/rosetta.git`
Then I entered the Rosetta folder and ran this command to build the image: `docker build -t flow .`

Please help me with the below error.

**I'm getting the below error at Step 11/12:**
Step 11/12 : RUN cd /app/src/rosetta-flow && go build -tags relic -o server cmd/server/server.go
 ---> Running in 1779d465f180
# github.com/onflow/flow-go/crypto
In file included from /root/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.24.3/bls.go:32:
/root/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.24.3/bls_include.h:8:10: fatal error: relic.h: No such file or directory
    8 | #include "relic.h"
      |          ^~~~~~~~~
compilation terminated.
The command '/bin/sh -c cd /app/src/rosetta-flow && go build -tags relic -o server cmd/server/server.go' returned a non-zero code: 2

**Comment by franklywatson** [comment]
Hey there Palak, 

We're curious to understand why you are interested to run Rosetta - it's purpose built for Coinbase's integration purposes and is highly unique to that use-case and not a recommended way to integrate Flow into a 3rd party system.

**Comment by Palak3196** [comment]
Hi franklywatson,

We ran into this link hoping it could work for us, as we specifically want the docker implementation.

Our initial attempt was at setting up an Access node following the Near official documents: https://docs.onflow.org/node-operation/node-setup/

Tried this command to bring up the container but it fails:
```
docker run --rm \
	-v /path/to/bootstrap:/bootstrap:ro \
	-v /path/to/data:/data:rw \
	--name flow-go \
	--network host \
	gcr.io/flow-container-registry/access:v0.25.7 \
	--nodeid=${FLOW_GO_NODE_ID} \
	--bootstrapdir=/bootstrap \
	--datadir=/data/protocol \
	--secretsdir=/data/secrets \
	--rpc-addr=0.0.0.0:9000 \
	--http-addr=0.0.0.0:8000 \
	--collection-ingress-port=9000 \
	--script-addr=${FLOW_NETWORK_EXECUTION_NODE} \
	--bind 0.0.0.0:3569 \
	--loglevel=error
```

If you have any expertise on this please let me know. Appreciate your help

Thanks,
Palak

**Comment by franklywatson** [comment]
Hi Palak, 

So you want to setup an Access Node? If so, this isn't the software package you would use to achieve this. Rosetta is a very particular integration for Flow blockchain to Coinbase Exchange for trading. In addition, if you wanted to run an Access node you would need permission to do so and some stake to run it. We are working on an unstaked lite-node equivalent solution but. that isn't going to be available until some time in August.

**Comment by Palak3196** [comment]
Hello,
Is the observer node ready to use now?

Thanks,
Palak

**Comment by franklywatson** [comment]
We just released it: https://developers.flow.com/nodes/node-operation
